---
- hosts: all
  name: Install yum package 
  tasks:
    - name: install httpd
      yum: 
        name: httpd
        state: latest
      register: install_result
    
    - debug: var=install_result
